config/routes.rb
Playlister::Application.routes.draw do
  devise_for :users
  get "songs/makesome" => "songs#make_songs", :as=> :make_songs

  resources :tours

  resources :genres

  resources :songs

  root 'artists#index'

  resources :artists

  

end

app/models/artist.rb
class Artist < ActiveRecord::Base
        ##rails 3 has this
        #attr_accessible :name, :record_label
    has_many :songs
    has_many :genres, through: :songs

    before_save :sluggify

    def sluggify
      self.slug = self.name.gsub(" ", "-").downcase
    end

    def add_song (song)
      #song.genre.artists << self
      self.songs<<song


    end

    def genres
      local_genres = []
      songs.each do |song|
        local_genres << song.genre
      end
      local_genres

    end

    def song_names= (names)
      names.each do |song_name|
        #or self.songs.build(:title=>song_name)
        song = Song.find_or_create_by(:title=>song_name)
        self.songs << song
      end
    end

    def song_names
      Rails.cache.fetch([:artist,self.id,:songs]) do

        local_names = []
        songs.each do |song|
          local_names << song.title
        end
        local_names
      end
    end

    def to_param
      self.sluggify unless self.slug
      self.slug
    end

    def self.find(val)
      if val.to_i != 0
        super val
      else
        find_by(:slug=>val)
      end

    end

  def self.find_by_genre(genre_name)
    #AREL
    #joins(:songs)
    #.joins(:genres)   # Artist doesn't know about genres
    #.where("genres.name ILIKE ?", genre_name)
    #joins("inner join songs on so")
    joins(:songs => :genre)
    .where("genres.name LIKE ?", genre_name)
    #.joins(:genres)   # Artist doesn't know about genres

  end

  def self.with_record_labels()
    where ("record_label is not null")
  end

  def self.with_specific_label(label)
    where(record_label: label)
  end
  #TYPES = %w[band solo]
  #validates :type, :inclusion => {:in=>Artist::TYPE}

end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_artist, only: [:show, :edit, :update, :destroy]
  before_action :get_main_artist

  skip_before_action :set_something, only: [:index]
  # GET /artists
  # GET /artists.json
  def index
    @artists = Artist.all

  end

  # GET /artists/1
  # GET /artists/1.json
  def show
    respond_to do |format|
      format.json {render json:@artist}
    end

  end

  # GET /artists/new
  def new
    @artist = Artist.new
  end

  # GET /artists/1/edit
  def edit
  end

  # POST /artists
  # POST /artists.json
  def create
    @artist = Artist.new(artist_params)

    respond_to do |format|
      if @artist.save
        format.html { redirect_to @artist, notice: 'Artist was successfully created.' }
        format.json { render action: 'show', status: :created, location: @artist }
      else
        format.html { render action: 'new' }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /artists/1
  # PATCH/PUT /artists/1.json
  def update
    respond_to do |format|
      if @artist.update(artist_params)
        format.html { redirect_to @artist, notice: 'Artist was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /artists/1
  # DELETE /artists/1.json
  def destroy
    @artist.destroy
    respond_to do |format|
      format.html { redirect_to artists_url }
      format.json { head :no_content }
    end
  end

  private

    def get_main_artist
      session[:main_artist] = "Moby"
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_artist
      @artist = Artist.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def artist_params
        #strong params over here, these check what can be updated 
      params.require(:artist).permit(:name, :record_label, :song_names=>[])
    end
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/views/artists/_form.html.erb
<%= form_for(@artist) do |f| %>

// form_tag

  <% if @artist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@artist.errors.count, "error") %> prohibited this artist from being saved:</h2>

      <ul>
      <% @artist.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :record_label %><br>
    <%= f.text_field :record_label %>
    
    <input type='text' id='artist_record_lable' name='artist[record_label]' value='<%=@artist.record_label%>'/>

  </div>
    <div class="field">
        <h4>Songs:</h4>
      <!-- not dealing with a direct attribute for rails  -->
        <%= text_field_tag "artist[song_names][]" %>  <br />
          <%= text_field_tag "artist[song_names][]" %>      <br />
          <%= text_field_tag "artist[song_names][]" %>            <br />
          <%= text_field_tag "artist[song_names][]" %>                  <br />
    </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/artists/edit.html.erb
<h1>Editing artist</h1>

<%= render 'form' %>

<%= link_to 'Show', @artist %> |
<%= link_to 'Back', artists_path %>

app/views/artists/index.html.erb
<h1>Listing artists</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Record label</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @artists.each do |artist| %>
      <tr>
        <td><%= artist.name %></td>
        <td><%= artist.record_label %></td>
        <td><%= link_to 'Show', artist %></td>
        <td><%= link_to 'Edit', edit_artist_path(artist) %></td>
        <td><%= link_to 'Destroy', artist, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'Make Songs', make_songs_path, :id=>"make_songs"%>
<%= link_to 'New Artist', new_artist_path %>

<script>
  $(document).ready(function(){
       $("#make_songs").on("click", function(){
           $.get('<%=make_songs_path%>', function(data){

           });
       })  ;
  })  ;
</script>

app/views/artists/new.html.erb
<h1>New artist</h1>

<%= render 'form' %>

<%= link_to 'Back', artists_path %>

app/views/artists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @artist.name %>
</p>

<p>
  <strong>Record label:</strong>
  <%= @artist.record_label %>
</p>

<p>
  <%= render 'songs/song_list', songs:@artist.songs %>
</p>

<%= link_to 'Edit', edit_artist_path(@artist) %> |
<%= link_to 'Back', artists_path %>