config/routes.rb
Playlister::Application.routes.draw do
  devise_for :users
  get "songs/makesome" => "songs#make_songs", :as=> :make_songs

  resources :tours

  resources :genres

  resources :songs

  root 'artists#index'

  resources :artists

  

end

app/models/song.rb
class Song < ActiveRecord::Base
    belongs_to :artist , touch:true #song has an artist id , touch true means that updates to artist which is a related model will update the dependent
    belongs_to :genre  #song has a  genre id

    validates :title, :presence => {:message=> "Every song has a name, enter one even if it's Untitled"  }
    #after_save fires only after a .save, after_commit is fired after every successful DB operation
    after_commit :invalidate_cache

    def invalidate_cache
      Rails.cache.clear([:artist,self.artist_id, :songs])
    end
    #reader for genre name
    def genre_name
      self.genre.name unless self.genre.nil?
    end

    def genre_name=(genre_name)
      #implicit instance variable
      @genre_name = genre_name
      #this is an upsert
      self.genre = Genre.find_or_create_by(:name=>genre_name)

    end
    #reader
    def artist_name
       self.artist.name unless self.artist.nil? 
    end
    #can do like this
    #attr_accessor :artist_name
    #but that doesn't get the whole connection of song to artist
    def artist_name=(artist_name)
        @artist_name = artist_name
        # this is the dumb way where we create each time
        # self.artist = Artist.create(:name => artist_name) 
        # this is nice and neat an upsert
        self.artist = Artist.find_or_create_by(:name => artist_name) 
    end
    
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_song, only: [:show, :edit, :update, :destroy]

  # GET /songs
  # GET /songs.json
  def index
    @songs = Song.all
  end

  def make_songs
    3.times do |i|
      Song.create(:title=>"new song #{i}")
    end
    render :partial => 'song_list', locals: {songs: Song.all}
  end

  # GET /songs/1
  # GET /songs/1.json
  def show
  end

  # GET /songs/new
  def new
    @song = Song.new
  end

  # GET /songs/1/edit
  def edit
  end

  # POST /songs
  # POST /songs.json
  def create
    @song = Song.new(song_params)
    ##Could do it like this but this is goofy  
    #@artist = Artist.new(params[:song][:artist_name])
    #if(Artist.find....)  
      
    respond_to do |format|
      if @song.save
        format.html { redirect_to @song, notice: 'Song was successfully created.' }
        format.json { render action: 'show', status: :created, location: @song }
      else
        format.html { render action: 'new' }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /songs/1
  # PATCH/PUT /songs/1.json
  def update
    respond_to do |format|
      if @song.update(song_params)
        format.html { redirect_to @song, notice: 'Song was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /songs/1
  # DELETE /songs/1.json
  def destroy
    @song.destroy
    respond_to do |format|
      format.html { redirect_to songs_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_song
      @song = Song.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def song_params
      params.require(:song).permit(:title, :artist_name, :genre_name)
    end
end

app/helpers/songs_helper.rb
module SongsHelper
  def show_song_label (song)
    begin
      html =  "<td>#{song.title}- by #{song.artist.name}"
      if song.artist.nil? == false  && song.artist.record_label.nil? == false
        html += " #{song.artist.record_label}" if song.artist.record_label.downcase.include? "epic"
      end
      html += "</td>"
    rescue
    end
    html
  end

end

app/views/songs/_form.html.erb
<%= form_for(@song) do |f| %>
  <% if @song.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@song.errors.count, "error") %> prohibited this song from being saved:</h2>

      <ul>
      <% @song.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
    <div class="field">
    <%= f.label :artist_name %><br>
    <%= f.text_field :artist_name %>
  </div>
    <div class="field">
      <%= f.label :genre_name %><br>
      <%= f.text_field :genre_name %>
    </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/songs/_song_list.html.erb
<table>
  <thead>
  <tr>
    <th>Title</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  </thead>

  <tbody>
  The html returned by the Song helper is escaped html, the raw(input) method allows to unenscape that and turn it into html
  as much as possible howeve don't use helpers for html.

  Also look at HereDoc   .

<%  songs.each do |song| %>
    <tr>
      <td><%= song.title %></td>

      <td><%= raw show_song_label song %></td>
      <td><%= link_to 'Show', song %></td>
      <td><%= link_to 'Edit', edit_song_path(song) %></td>
      <td><%= link_to 'Destroy', song, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
<% end %>

  </tbody>
</table>

<br>

app/views/songs/edit.html.erb
<h1>Editing song</h1>

<%= render 'form' %>

<%= link_to 'Show', @song %> |
<%= link_to 'Back', songs_path %>

app/views/songs/index.html.erb
Current User: <%= current_user %>
<h1>Listing songs</h1>
<div id="songs_list">

  <% cache @songs do %>
    <%= render 'song_list', songs:@songs    %>
  <% end %>
</div>

<%= link_to 'New Song', new_song_path %>

<%= link_to 'Make Songs', make_songs_path, :id=>"make_songs", :href=>"#"%>


<script>
    $(document).ready(function(){
        $("#make_songs").on("click", function(){
            $.get('<%=make_songs_path%>', function(data){
                  $("#songs_list").html(data);
            });
        })  ;
    })  ;
</script>

app/views/songs/new.html.erb
<h1>New song</h1>

<%= render 'form' %>

<%= link_to 'Back', songs_path %>

app/views/songs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @song.title %>
</p>

<%= link_to 'Edit', edit_song_path(@song) %> |
<%= link_to 'Back', songs_path %>