config/routes.rb
Playlister::Application.routes.draw do
  devise_for :users
  get "songs/makesome" => "songs#make_songs", :as=> :make_songs

  resources :tours

  resources :genres

  resources :songs

  root 'artists#index'

  resources :artists

  

end

app/models/tour.rb
class Tour < ActiveRecord::Base
end

app/controllers/tours_controller.rb
class ToursController < ApplicationController
  before_action :set_tour, only: [:show, :edit, :update, :destroy]

  # GET /tours
  # GET /tours.json
  def index
    @tours = Tour.all
  end

  # GET /tours/1
  # GET /tours/1.json
  def show
  end

  # GET /tours/new
  def new
    @tour = Tour.new
  end

  # GET /tours/1/edit
  def edit
  end

  # POST /tours
  # POST /tours.json
  def create
    @tour = Tour.new(tour_params)

    respond_to do |format|
      if @tour.save
        format.html { redirect_to @tour, notice: 'Tour was successfully created.' }
        format.json { render action: 'show', status: :created, location: @tour }
      else
        format.html { render action: 'new' }
        format.json { render json: @tour.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tours/1
  # PATCH/PUT /tours/1.json
  def update
    respond_to do |format|
      if @tour.update(tour_params)
        format.html { redirect_to @tour, notice: 'Tour was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @tour.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tours/1
  # DELETE /tours/1.json
  def destroy
    @tour.destroy
    respond_to do |format|
      format.html { redirect_to tours_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tour
      @tour = Tour.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tour_params
      params.require(:tour).permit(:name)
    end
end

app/views/tours/_form.html.erb
<%= form_for(@tour) do |f| %>
  <% if @tour.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tour.errors.count, "error") %> prohibited this tour from being saved:</h2>

      <ul>
      <% @tour.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tours/edit.html.erb
<h1>Editing tour</h1>

<%= render 'form' %>

<%= link_to 'Show', @tour %> |
<%= link_to 'Back', tours_path %>

app/views/tours/index.html.erb
<h1>Listing tours</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @tours.each do |tour| %>
      <tr>
        <td><%= tour.name %></td>
        <td><%= link_to 'Show', tour %></td>
        <td><%= link_to 'Edit', edit_tour_path(tour) %></td>
        <td><%= link_to 'Destroy', tour, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tour', new_tour_path %>

app/views/tours/new.html.erb
<h1>New tour</h1>

<%= render 'form' %>

<%= link_to 'Back', tours_path %>

app/views/tours/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @tour.name %>
</p>

<%= link_to 'Edit', edit_tour_path(@tour) %> |
<%= link_to 'Back', tours_path %>